name: Data Integration Workflow

on:
  # Allows manual triggering of the workflow
  workflow_dispatch:
  # Triggers the workflow on push to the main branch and specific paths
  push:
    branches:
      - main
    paths:
      - 'data-hub/'
      - 'scripts/'
  # Triggers on pull request affecting specific paths on main
  pull_request:
    branches:
      - main
    paths:
      - 'data-hub/'

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run Linter on Shell Scripts
        run: shellcheck scripts/*.sh

  monitor_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Monitor Folders for Changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            data:
              - 'data-hub/'
              - 'db/'

      - name: Print Changed Folders
        run: |
          echo "Data folder changed: ${{ steps.changes.outputs.data }}"

  data_integration:
    runs-on: ubuntu-latest
    needs: monitor_changes
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Make Script Executable
        run: chmod +x scripts/data_integration.sh

      - name: Run Data Integration Script
        run: ./scripts/data_integration.sh

      - name: Check the Updated Dataset
        run: wc -l db/database.csv

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Nsuccess"
          git config --global user.email "successnwachukwu368@gmail.com"
          git add db/database.csv
          git commit -m "Automated Integration Script"
          git push origin main
